# This is a configuration file for markdownlint or
# rather markdownlint-cli. See
#
#   https://github.com/DavidAnson/markdownlint
#
# for details.


# Enable all default rules (to later override/adjust).
default: true

# Consistent bullets
MD004:
  style: consistent

MD007:
  indent: 4

# MD009/no-trailing-spaces
#
# We explicitly don't want trailing spaces. Authors' editors should be configured to trim them. The Markdown feature of
# using two spaces at the end of a line should not be used (use the alternative `<br>` only if really necessary, or
# better use normal paragraphs).
MD009: true

# Ignore front matter in headline linting
MD025:
  front_matter_title: ""

# Allow for intuitive numbered lists
MD029:
  style: ordered

# Ignore inline HTML. We need this in certain places
MD033: false

# Ignore bare URLs, as this does not work with HUGO shortcodes
MD034: false

# Enforcing the rules below will require big changes in the entire repo.
# So we exclude them for now.

# Don't lint for line length
MD013: false

# MD051/link-fragments
#
# We use GitHub's format (`## My heading {#explicit-reference-name}`) in some cases but markdownlint only supports
# the regular CommonMark specification for the aliases (see https://github.com/DavidAnson/markdownlint/blob/main/doc/md051.md).
# The lint is therefore not helpful.
MD051: false

# MD052/reference-links-images
#
# We use the Hugo functionality such as `[1]: {{< relref "..." >}}` which markdownlint recognizes as undefined reference,
# so the lint is not helpful.
MD052: false

MD046:
  style: fenced
