# Configuration file for crd-docs-generator
source_repository:
  url: https://github.com/giantswarm/apiextensions
  organization: giantswarm
  short_name: apiextensions
  commit_reference: v0.3.4
skip_crds:
  - chartconfigs.core.giantswarm.io
  - clusters.core.giantswarm.io
  - draughtsmanconfigs.core.giantswarm.io
  - ingressconfigs.core.giantswarm.io
  - memcachedconfigs.example.giantswarm.io
  - releasecycles.release.giantswarm.io
