version: "2"
services:

  docs-app:
    # to build this image locally, execute 'make docker-build'
    image: quay.io/giantswarm/docs:latest

  sitesearch-app:
    image: elasticsearch:6.8.6
    platform: linux/amd64
    environment:
      - cluster.name=sitesearch
      - node.name=sitesearch1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "ES_HOME=/usr/share/elasticsearch"
    ports:
      - 9200:9200
    volumes:
      - $PWD/volumes/elasticsearch-logs:/usr/share/elasticsearch/data
      - $PWD/volumes/elasticsearch-data:/usr/share/elasticsearch/logs

  api-spec-app:
    image: quay.io/giantswarm/api-spec:latest

  proxy:
    image: quay.io/giantswarm/docs-proxy:latest
    depends_on:
      - sitesearch-app
      - docs-app
      - api-spec-app
    volumes:
      - ./test/certificate:/etc/nginx/certs
    ports:
      - "8000:8000"

  internal-search-proxy-app:
    image: quay.io/giantswarm/oauth2_proxy:v5.1.0
    command: >
      --provider=github
      --github-org=giantswarm
      --github-team=employees
      --email-domain=*
      --upstream=http://sitesearch-app:9200
      --http-address=0.0.0.0:4180
      --cookie-domain=.giantswarm.io
      --cookie-secret foo
      --client-id bar
      --client-secret sfdsdf
    depends_on:
      - sitesearch-app
    ports:
      - "4180:4180"

  indexer-docs:
    image: quay.io/giantswarm/docs-indexer:latest
    command: hugo
    restart: "no"
    depends_on:
      - sitesearch-app
    environment:
      ELASTICSEARCH_ENDPOINT: http://sitesearch-app:9200
      REPOSITORY_HANDLE: giantswarm/docs
      REPOSITORY_BRANCH: main
      REPOSITORY_SUBFOLDER: src/content
      INDEX_NAME: docs
      TYPE_LABEL: Documentation
      BASE_URL: https://docs.giantswarm.io/
      APIDOCS_BASE_URI: https://docs.giantswarm.io/api/
      APIDOCS_BASE_PATH: /api/
      API_SPEC_FILES: yaml/spec.yaml,yaml/definitions.yaml,yaml/parameters.yaml,yaml/responses.yaml

  indexer-intranet:
    image: quay.io/giantswarm/docs-indexer:latest
    command: hugo
    restart: "no"
    depends_on:
      - sitesearch-app
    environment:
      ELASTICSEARCH_ENDPOINT: http://sitesearch-app:9200
      REPOSITORY_HANDLE: giantswarm/giantswarm
      REPOSITORY_BRANCH: main
      REPOSITORY_SUBFOLDER: content/docs
      INDEX_NAME: intranet
      TYPE_LABEL: Intranet
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      BASE_URL: https://intranet.giantswarm.io/

  indexer-handbook:
    image: quay.io/giantswarm/docs-indexer:latest
    command: hugo
    restart: "no"
    depends_on:
      - sitesearch-app
    environment:
      ELASTICSEARCH_ENDPOINT: http://sitesearch-app:9200
      REPOSITORY_HANDLE: giantswarm/handbook
      REPOSITORY_BRANCH: main
      REPOSITORY_SUBFOLDER: content
      INDEX_NAME: handbook
      TYPE_LABEL: Handbook
      BASE_URL: https://handbook.giantswarm.io/

  indexer-blog:
    image: quay.io/giantswarm/docs-indexer:latest
    command: blog
    restart: "no"
    depends_on:
      - sitesearch-app
    environment:
      ELASTICSEARCH_ENDPOINT: http://sitesearch-app:9200
      HUBSPOT_ACCESS_TOKEN: ${HUBSPOT_ACCESS_TOKEN}
