version: "2"
services:

  docs-app:
    # to build this image locally, execute 'make'
    image: quay.io/giantswarm/docs:latest

  sitesearch-app:
    image: quay.io/giantswarm/sitesearch:latest

  api-spec-app:
    image: quay.io/giantswarm/api-spec:latest

  proxy:
    image: quay.io/giantswarm/docs-proxy:latest
    depends_on:
      - sitesearch-app
      - docs-app
      - api-spec-app
    volumes:
      - ./test/certificate:/etc/nginx/certs
    ports:
      - "8000:8000"

  indexer:
    image: quay.io/giantswarm/docs-indexer:latest
    restart: on-failure
    depends_on:
      - sitesearch-app
    environment:
      REPOSITORY_URL: https://github.com/giantswarm/docs.git
      REPOSITORY_BRANCH: master
      REPOSITORY_SUBFOLDER: src/content
      EXTERNAL_REPOSITORY_SUBFOLDER: docs
      ELASTICSEARCH_ENDPOINT: http://admin:e4dfbjb3rohi8qpoadsffodin@sitesearch-app:9200
      APIDOCS_BASE_URI: https://docs.giantswarm.io/api/
      API_SPEC_FILES: yaml/spec.yaml,yaml/definitions.yaml,yaml/parameters.yaml,yaml/responses.yaml
      APIDOCS_BASE_PATH: /api/
