version: "3"
services:
  docs-app:
    # to build this image locally, execute 'make docker-build'
    image: gsoci.azurecr.io/giantswarm/docs:latest
    container_name: docs-app
    ports:
      - "8080:8080"