apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 3.0.0
    app.kubernetes.io/name: docs-staging-app
  name: docs-staging-app
  namespace: c68pn
spec:
  catalog: giantswarm-operations-platform-test
  config:
    configMap:
      name: c68pn-cluster-values
      namespace: c68pn
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: giantswarm-c68pn-context
    inCluster: false
    secret:
      name: c68pn-kubeconfig
      namespace: c68pn
  name: docs-staging-app
  namespace: docs
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 2650332d9216a45a8d9cd575666d478aef4943ab
