apiVersion: v1
# TODO: revert from docs-staging-app to docs-app
name: docs-staging-app
namespace: docs
appVersion: 0.0.1
description: Giant Swarm documentation published at https://docs.giantswarm.io/
home: https://github.com/giantswarm/docs/
version: "[[.Version]]"
