{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "resource.dex.name" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
{{- end }}
