{{- if (((.Values.global).podSecurityStandards).enforced) }}
---
apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
  labels:
    policy.giantswarm.io/resource-kind: Deployment
    policy.giantswarm.io/resource-name: {{ .Values.name }}
    policy.giantswarm.io/resource-namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-deployment
  namespace: policy-exceptions
spec:
  policies:
    - disallow-capabilities-strict
    - disallow-privilege-escalation
    - require-run-as-nonroot
    - restrict-seccomp-strict
  targets:
    - kind: Deployment
      names:
        - {{ .Values.name }}*
      namespaces:
        - {{ .Release.Namespace }}
{{- end }}
