kind: Service
apiVersion: v1
metadata:
  namespace: docs
  name: content
  labels:
    app: docs
    component: content
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: docs
    component: content
