kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: content
  labels:
    app: {{ .Values.image.name }}
    component: content
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: {{ .Values.image.name }}
    component: content
