{
 "title": "Helloworld",
 "time": { "from": "2024-01-01T00:00:48.548Z", "to": "2024-12-31T00:00:10.645Z" },
 "panels": [
  {
   "title": "Number of successful requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(promhttp_metric_handler_requests_total{container=\"hello-world\",code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of error requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(promhttp_metric_handler_requests_total{container=\"hello-world\",code=\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(promhttp_metric_handler_requests_total{container=\"hello-world\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}