apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: silences-customer-delete-{CLUSTER-ID}
  namespace: {YOUR_ORGANIZATION}
  labels:
    app: silence-customer
spec:
  schedule: "00 8 * * 1" #Timezone - UTC by default - Mondays, 8 AM UTC
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: silences-customer
        spec:
          serviceAccountName: silences-customer-rbac
          containers:
          - name: silences-customer-delete-{CLUSTER-ID}
            image: quay.io/giantswarm/k8s-initiator
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |

              kubectl patch MachinePool -n {YOUR_ORGANIZATION} {CLUSTER-ID} --type merge -p '{"metadata" : {"annotations": {"cluster.k8s.io/cluster-api-autoscaler-node-group-min-size": "1"}}}'
              kubectl patch MachinePool -n {YOUR_ORGANIZATION} {CLUSTER-ID} --type merge -p '{"metadata" : {"annotations": {"cluster.k8s.io/cluster-api-autoscaler-node-group-max-size": "3"}}}'

              # Please let the 10minutes in for the workers to appear and initial workloads to be deployed on the cluster.
              sleep 10m

              kubectl delete silence {INSTALLATION}-{CLUSTER-ID}-silence-cluster

          restartPolicy: Never
