baseurl = "https://docs.giantswarm.io"
languageCode = "en"
title = "Giant Swarm Documentation"
pluralizeListTitles = false
rssLimit = 50

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel = 5
    startLevel = 1

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      codeFences = true
      style = "solarized-dark"
      guessSyntax = false
      tabWidth = 4
      lineNos = false

[[menu.main]]
    name = "Basics and Concepts"
    url = "/basics/"
    weight = 20
[[menu.main]]
    name = "User Guides"
    url = "/guides/"
    weight = 30
[[menu.main]]
    name = "Reference"
    url = "/reference/"
    weight = 40
[[menu.main]]
    name = "Changes"
    url = "/changes/"
    weight = 50
[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 60

[taxonomies]
  changes_category = "changes_categories"

[permalinks]
  changes_categories = "/changes/:slug"
