baseurl = "https://docs.giantswarm.io"
languageCode = "en"
title = "Giant Swarm Documentation"
pluralizeListTitles = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel = 5
    startLevel = 1

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter, as we use highlight.js

[[menu.main]]
    name = "Basics and Concepts"
    url = "/basics/"
    weight = 20
[[menu.main]]
    name = "User Guides"
    url = "/guides/"
    weight = 30
[[menu.main]]
    name = "Reference"
    url = "/reference/"
    weight = 40
[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 50
