# This workflow verifies hyperlinks using the deployed
# docs site. It has to be triggered manually.
name: Check links

on:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Pull images
        run: docker pull ghcr.io/linkchecker/linkchecker:latest

      - name: Check links in overview pages
        run: |
          docker run --rm --name linkchecker \
            ghcr.io/linkchecker/linkchecker:latest \
            https://docs.giantswarm.io/overview/ \
            --check-extern \
            -t 1 -r 2

      - name: Check links in getting-started pages
        run: |
          docker run --rm --name linkchecker \
            ghcr.io/linkchecker/linkchecker:latest \
            https://docs.giantswarm.io/getting-started/ \
            --check-extern \
            -t 1-r 2

      - name: Check links in tutorials pages
        run: |
          docker run --rm --name linkchecker \
            ghcr.io/linkchecker/linkchecker:latest \
            https://docs.giantswarm.io/tutorials/ \
            --check-extern \
            -t 1 -r 2

      - name: Check links in reference pages
        run: |
          docker run --rm --name linkchecker \
            ghcr.io/linkchecker/linkchecker:latest \
            https://docs.giantswarm.io/reference/ \
            --check-extern \
            -t 1 -r 2

      - name: Check links in support pages
        run: |
          docker run --rm --name linkchecker \
            ghcr.io/linkchecker/linkchecker:latest \
            https://docs.giantswarm.io/support/ \
            --check-extern \
            -t 1 -r 2

      - name: Check links in changelogs
        run: |
          docker run --rm --name linkchecker \
            ghcr.io/linkchecker/linkchecker:latest \
            https://docs.giantswarm.io/changes/ \
            -t 1 -r 2 \
            --ignore-url="^https://github.com/giantswarm/docs/.*" \
            --ignore-url="^https://.*example\.com/.*" \
            --ignore-url="^https://my-org\.github\.com/.*" \
            --ignore-url="^https://github\.com/giantswarm/giantswarm/.*" \
            --ignore-url=".*gigantic\.io.*"
