name: Generate review PRs
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**.md'

jobs:
  front-matter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip3 install click colored

      - name: Validate front matter for changed files
        run: |
          git fetch --no-tags origin "${GITHUB_BASE_REF}":"${GITHUB_BASE_REF}"
          git diff --name-only "refs/heads/${GITHUB_BASE_REF}" -- . | tee files.txt
          cat files.txt | python3 scripts/validate-front-matter/script.py
      
      - name: Verify annotations
        run: cat ./annotations.json
      
      - name: Check if the issue already exists
        run: |
          jq -c '.[]' ./annotations.json | while read i; do
            echo $i
          done
