name: Create release on merge

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'do not release')"
    steps:

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          omitBody: true
          name: Release ${{ steps.tag_version.outputs.new_tag }}

