name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'do not release')"
    steps:
      - name: Create Release
        id: create_release
        uses: zendesk/action-create-release@v1
        with:
          tag_schema: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
